<?xml version="1.0" standalone="yes"?>

<?program_dtd version="1"?>

<!DOCTYPE PROGRAM [

<!ELEMENT PROGRAM (DESCRIPTION?,
                   INFO_SOURCE?,
                   PROCESSOR?,
                   COMPILER?,
                   DATATYPES?,
                   MEMORY_MAP?,
                   REGISTER_VALUES?,
                   CODE?,
                   DATA?,
                   EQUATES?,
                   COMMENTS?,
                   PROPERTIES?,
                   BOOKMARKS?,
                   PROGRAM_TREES?,
                   PROGRAM_ENTRY_POINTS?,
                   RELOCATION_TABLE?,
                   SYMBOL_TABLE?,
                   FUNCTIONS?,
                   MARKUP?,
                   EXT_LIBRARY_TABLE?)>
  <!ATTLIST PROGRAM NAME       CDATA #REQUIRED>
  <!ATTLIST PROGRAM EXE_PATH   CDATA #IMPLIED>
  <!ATTLIST PROGRAM EXE_FORMAT CDATA #IMPLIED>
  <!ATTLIST PROGRAM IMAGE_BASE CDATA #IMPLIED>

<!ELEMENT DISPLAY_SETTINGS EMPTY>
  <!ATTLIST DISPLAY_SETTINGS FORMAT           (hex | decimal | octal | binary | char) #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SIGNED           (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ZERO_PAD         (y | n)                                 #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS ENDIAN           (big | little)                          #IMPLIED>
  <!ATTLIST DISPLAY_SETTINGS SHOW_TERMINATOR  (y | n)                                 #IMPLIED>

<!ELEMENT DESCRIPTION    (#PCDATA)>
<!ELEMENT REGULAR_CMT    (#PCDATA)>
<!ELEMENT REPEATABLE_CMT (#PCDATA)>
<!ELEMENT TYPEINFO_CMT   (#PCDATA)>

<!ELEMENT INFO_SOURCE EMPTY>
  <!ATTLIST INFO_SOURCE USER      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TOOL      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE FILE      CDATA #IMPLIED>
  <!ATTLIST INFO_SOURCE TIMESTAMP CDATA #IMPLIED>

<!ELEMENT PROCESSOR EMPTY>
  <!ATTLIST PROCESSOR NAME              CDATA          #REQUIRED>
  <!ATTLIST PROCESSOR FAMILY            CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR LANGUAGE_PROVIDER CDATA          #IMPLIED>
  <!ATTLIST PROCESSOR ENDIAN            (big | little) #IMPLIED>
  <!ATTLIST PROCESSOR ADDRESS_MODEL     CDATA          #IMPLIED>

<!-- TODO: expand compiler tag -->
<!ELEMENT COMPILER EMPTY>
  <!ATTLIST COMPILER NAME CDATA #REQUIRED>

<!ELEMENT MEMORY_MAP (MEMORY_SECTION*)>

<!ELEMENT MEMORY_SECTION ((MEMORY_CONTENTS*) | (BIT_MAPPED?))>
  <!ATTLIST MEMORY_SECTION NAME         CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION START_ADDR   CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION LENGTH       CDATA                             #REQUIRED>
  <!ATTLIST MEMORY_SECTION PERMISSIONS  (r | w | x | rw | rx | wx | rwx)  #IMPLIED>
  <!ATTLIST MEMORY_SECTION VOLATILE     (y | n)                           #IMPLIED>
  <!ATTLIST MEMORY_SECTION COMMENT      CDATA                             #IMPLIED>

<!ELEMENT MEMORY_CONTENTS EMPTY>
  <!ATTLIST MEMORY_CONTENTS START_ADDR   CDATA  #IMPLIED>
  <!ATTLIST MEMORY_CONTENTS FILE_NAME    CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS FILE_OFFSET  CDATA  #REQUIRED>
  <!ATTLIST MEMORY_CONTENTS LENGTH       CDATA  #IMPLIED>

<!ELEMENT BIT_MAPPED EMPTY>
  <!ATTLIST BIT_MAPPED SOURCE_ADDRESS  CDATA  #REQUIRED>

<!ELEMENT REGISTER_VALUES (REGISTER_VALUE_RANGE*)>

<!ELEMENT REGISTER_VALUE_RANGE EMPTY>
  <!ATTLIST REGISTER_VALUE_RANGE REGISTER      CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE VALUE         CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE START_ADDRESS CDATA #REQUIRED>
  <!ATTLIST REGISTER_VALUE_RANGE LENGTH        CDATA #REQUIRED>

<!ELEMENT CODE (CODE_BLOCK*)>

<!ELEMENT CODE_BLOCK EMPTY>
  <!ATTLIST CODE_BLOCK  START  CDATA  #REQUIRED>
  <!ATTLIST CODE_BLOCK  END    CDATA  #REQUIRED>

<!ELEMENT DATA (DEFINED_DATA*)>

<!ELEMENT DEFINED_DATA (TYPEINFO_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST DEFINED_DATA ADDRESS             CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST DEFINED_DATA DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST DEFINED_DATA SIZE                CDATA  #IMPLIED>

<!ELEMENT EQUATES (EQUATE_GROUP*)>

<!ELEMENT EQUATE_GROUP (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, (EQUATE | BIT_MASK)*)>
  <!ATTLIST EQUATE_GROUP NAME       CDATA       #IMPLIED>
  <!ATTLIST EQUATE_GROUP BIT_FIELD  (yes | no)  #IMPLIED>

<!ELEMENT EQUATE (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST EQUATE NAME     CDATA  #REQUIRED>
  <!ATTLIST EQUATE VALUE    CDATA  #REQUIRED>
  <!ATTLIST EQUATE BIT_MASK CDATA  #IMPLIED>

<!ELEMENT BIT_MASK (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST BIT_MASK NAME   CDATA  #REQUIRED>
  <!ATTLIST BIT_MASK VALUE  CDATA  #REQUIRED>

<!ELEMENT COMMENTS (COMMENT*)>

<!ELEMENT COMMENT (#PCDATA)>
  <!ATTLIST COMMENT ADDRESS  CDATA                                            #REQUIRED>
  <!ATTLIST COMMENT TYPE     (end-of-line | repeatable | pre | post | plate)  #REQUIRED>

<!ELEMENT PROPERTIES (PROPERTY*)>

<!ELEMENT PROPERTY EMPTY>
  <!ATTLIST PROPERTY NAME     CDATA                                                #REQUIRED>
  <!ATTLIST PROPERTY ADDRESS  CDATA                                                #IMPLIED>
  <!ATTLIST PROPERTY TYPE     (string | long | int | double | void | bool | date | custom)  #IMPLIED>
  <!ATTLIST PROPERTY VALUE    CDATA                                                #IMPLIED>

<!ELEMENT BOOKMARKS (BOOKMARK*)>

<!ELEMENT BOOKMARK EMPTY>
  <!ATTLIST BOOKMARK ADDRESS     CDATA  #REQUIRED>
  <!ATTLIST BOOKMARK TYPE        CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK CATEGORY    CDATA  #IMPLIED>
  <!ATTLIST BOOKMARK DESCRIPTION CDATA  #IMPLIED>

<!ELEMENT PROGRAM_TREES (TREE*)>

<!ELEMENT TREE ((FOLDER | FRAGMENT)*)>
  <!ATTLIST TREE NAME CDATA #REQUIRED>

<!ELEMENT FOLDER ((FOLDER | FRAGMENT)*)>
  <!ATTLIST FOLDER NAME CDATA #REQUIRED>

<!ELEMENT FRAGMENT (ADDRESS_RANGE)*>
  <!ATTLIST FRAGMENT NAME CDATA #REQUIRED>

<!ELEMENT ADDRESS_RANGE EMPTY>
  <!ATTLIST ADDRESS_RANGE START  CDATA  #REQUIRED>
  <!ATTLIST ADDRESS_RANGE END    CDATA  #REQUIRED>

<!ELEMENT PROGRAM_ENTRY_POINTS (PROGRAM_ENTRY_POINT*)>

<!ELEMENT PROGRAM_ENTRY_POINT EMPTY>
  <!ATTLIST PROGRAM_ENTRY_POINT  ADDRESS  CDATA  #REQUIRED>

<!ELEMENT RELOCATION_TABLE (RELOCATION*)>

<!ELEMENT RELOCATION EMPTY>
  <!ATTLIST RELOCATION ADDRESS  	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION STATUS    	( UNKNOWN | SKIPPED | UNSUPPORTED | FAILURE | PARTIAL | APPLIED | APPLIED_OTHER )	#IMPLIED>
  <!-- STATUS defaults to APPLIED if BYTES specified and TYPE is non-zero  -->
  <!-- STATUS defaults to APPLIED_OTHER if BYTES specified and TYPE is zero  -->
  <!-- STATUS defaults to UNKNOWN if BYTES are not specified  -->
  <!ATTLIST RELOCATION TYPE     	CDATA	#REQUIRED>
  <!ATTLIST RELOCATION VALUE    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION BYTES    	CDATA	#IMPLIED>
  <!ATTLIST RELOCATION SYMBOL_NAME	CDATA	#IMPLIED>

<!ELEMENT SYMBOL_TABLE (SYMBOL*)>

<!ELEMENT SYMBOL EMPTY>
  <!ATTLIST SYMBOL ADDRESS   		CDATA            					 #REQUIRED>
  <!ATTLIST SYMBOL NAME      		CDATA             					 #REQUIRED>
  <!ATTLIST SYMBOL NAMESPACE 		CDATA             					 #IMPLIED>
  <!ATTLIST SYMBOL TYPE      		(global | local)  					 #IMPLIED>
  <!ATTLIST SYMBOL SOURCE_TYPE      (USER_DEFINED | IMPORTED | ANALYSIS) #IMPLIED>
  <!ATTLIST SYMBOL PRIMARY   		(y | n)           					 #IMPLIED>
  <!ATTLIST SYMBOL MANGLED   		CDATA             					 #IMPLIED>

<!ELEMENT FUNCTIONS (FUNCTION*)>

<!ELEMENT FUNCTION (RETURN_TYPE?, ADDRESS_RANGE*, REGULAR_CMT?, REPEATABLE_CMT?, TYPEINFO_CMT?, STACK_FRAME?, REGISTER_VAR*)>
  <!ATTLIST FUNCTION ENTRY_POINT       CDATA   #REQUIRED>
  <!ATTLIST FUNCTION NAME              CDATA   #IMPLIED>
  <!-- TODO: create xml attrs for each known attribute type -->
  <!ATTLIST FUNCTION LIBRARY_FUNCTION  (y | n) #IMPLIED>

<!ELEMENT RETURN_TYPE EMPTY>
  <!ATTLIST RETURN_TYPE DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST RETURN_TYPE DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST RETURN_TYPE SIZE                CDATA  #IMPLIED>

<!ELEMENT STACK_FRAME (STACK_VAR*)>
  <!ATTLIST STACK_FRAME LOCAL_VAR_SIZE         CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME PARAM_OFFSET           CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME REGISTER_SAVE_SIZE     CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME RETURN_ADDR_SIZE       CDATA    #IMPLIED>
  <!ATTLIST STACK_FRAME BYTES_PURGED           CDATA    #IMPLIED>

<!ELEMENT STACK_VAR (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST STACK_VAR STACK_PTR_OFFSET    CDATA  #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_VAR FRAME_PTR_OFFSET    CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR NAME                CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST STACK_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST STACK_VAR SIZE                CDATA  #IMPLIED>

<!ELEMENT REGISTER_VAR (REGULAR_CMT?)>
  <!ATTLIST REGISTER_VAR NAME                CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR REGISTER            CDATA  #REQUIRED>
  <!ATTLIST REGISTER_VAR DATATYPE            CDATA  #IMPLIED>
  <!ATTLIST REGISTER_VAR DATATYPE_NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT MARKUP (MEMORY_REFERENCE      |
                  STACK_REFERENCE       |
                  EXT_LIBRARY_REFERENCE |
                  EQUATE_REFERENCE      |
                  MANUAL_OPERAND        |
                  MANUAL_INSTRUCTION)*>

<!-- An OPERAND_INDEX is omitted for a mnemonic reference    -->
<!-- The first operand is identified with OPERAND_INDEX=0 -->
<!ELEMENT MEMORY_REFERENCE EMPTY>
  <!ATTLIST MEMORY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE TO_ADDRESS     CDATA    #REQUIRED>
  <!ATTLIST MEMORY_REFERENCE BASE_ADDRESS   CDATA    #IMPLIED>
  <!ATTLIST MEMORY_REFERENCE PRIMARY        (y | n)  #IMPLIED>

<!ELEMENT STACK_REFERENCE EMPTY>
  <!ATTLIST STACK_REFERENCE ADDRESS          CDATA    #REQUIRED>
  <!ATTLIST STACK_REFERENCE OPERAND_INDEX    CDATA    #IMPLIED>
  <!ATTLIST STACK_REFERENCE USER_DEFINED     (y | n)  #IMPLIED>
  <!ATTLIST STACK_REFERENCE STACK_PTR_OFFSET CDATA    #REQUIRED> <!-- offset from the stack ptr value at function entry -->
  <!ATTLIST STACK_REFERENCE FRAME_PTR_OFFSET CDATA    #IMPLIED>

<!ELEMENT EXT_LIBRARY_REFERENCE EMPTY>
  <!ATTLIST EXT_LIBRARY_REFERENCE ADDRESS        CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE OPERAND_INDEX  CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE USER_DEFINED   (y | n)  #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_PROG_NAME  CDATA    #REQUIRED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_LABEL      CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ORDINAL    CDATA    #IMPLIED>
  <!ATTLIST EXT_LIBRARY_REFERENCE LIB_ADDR       CDATA    #IMPLIED>

<!ELEMENT EQUATE_REFERENCE EMPTY>
  <!ATTLIST EQUATE_REFERENCE ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE OPERAND_INDEX  CDATA  #IMPLIED>
  <!ATTLIST EQUATE_REFERENCE NAME           CDATA  #REQUIRED>
  <!ATTLIST EQUATE_REFERENCE VALUE          CDATA  #IMPLIED>

<!ELEMENT MANUAL_OPERAND (#PCDATA)>
  <!ATTLIST MANUAL_OPERAND ADDRESS        CDATA  #REQUIRED>
  <!ATTLIST MANUAL_OPERAND OPERAND_INDEX  CDATA  #REQUIRED>

<!ELEMENT MANUAL_INSTRUCTION (#PCDATA)>
  <!ATTLIST MANUAL_INSTRUCTION ADDRESS CDATA #REQUIRED>

<!ELEMENT EXT_LIBRARY_TABLE (EXT_LIBRARY*)>

<!ELEMENT EXT_LIBRARY EMPTY>
  <!ATTLIST EXT_LIBRARY NAME  CDATA  #REQUIRED>
  <!ATTLIST EXT_LIBRARY PATH  CDATA  #IMPLIED>

<!-- ************************************************************* -->
<!--                                                               -->
<!--                Data DTD                                       -->
<!--                                                               -->
<!-- ************************************************************* -->

<!ELEMENT DATATYPES (STRUCTURE | UNION | FUNCTION_DEF | ENUM | TYPE_DEF)*>

<!ELEMENT MEMBER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST MEMBER OFFSET              CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST MEMBER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST MEMBER NAME                CDATA  #IMPLIED>
  <!ATTLIST MEMBER SIZE                CDATA  #IMPLIED>

<!ELEMENT STRUCTURE (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST STRUCTURE NAME             CDATA   #REQUIRED>
  <!ATTLIST STRUCTURE NAMESPACE        CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE SIZE             CDATA   #IMPLIED>
  <!ATTLIST STRUCTURE VARIABLE_LENGTH  (y | n) #IMPLIED>

<!ELEMENT UNION (REGULAR_CMT?, REPEATABLE_CMT?, MEMBER*)>
  <!ATTLIST UNION NAME       CDATA  #REQUIRED>
  <!ATTLIST UNION NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST UNION SIZE       CDATA  #IMPLIED>

<!ELEMENT FUNCTION_DEF (REGULAR_CMT?, REPEATABLE_CMT?, RETURN_TYPE?, PARAMETER*)>
  <!ATTLIST FUNCTION_DEF NAME       CDATA  #REQUIRED>
  <!ATTLIST FUNCTION_DEF NAMESPACE  CDATA  #IMPLIED>

<!ELEMENT PARAMETER (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?)>
  <!ATTLIST PARAMETER ORDINAL             CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE            CDATA  #REQUIRED>
  <!ATTLIST PARAMETER DATATYPE_NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST PARAMETER NAME                CDATA  #IMPLIED>
  <!ATTLIST PARAMETER SIZE                CDATA  #IMPLIED>

<!ELEMENT TYPE_DEF (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST TYPE_DEF NAME                CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF NAMESPACE           CDATA #IMPLIED>
  <!ATTLIST TYPE_DEF DATATYPE            CDATA #REQUIRED>
  <!ATTLIST TYPE_DEF DATATYPE_NAMESPACE  CDATA #IMPLIED>

<!ELEMENT ENUM (REGULAR_CMT?, REPEATABLE_CMT?, DISPLAY_SETTINGS?, ENUM_ENTRY*)>
  <!ATTLIST ENUM NAME       CDATA  #REQUIRED>
  <!ATTLIST ENUM NAMESPACE  CDATA  #IMPLIED>
  <!ATTLIST ENUM SIZE       CDATA  #IMPLIED>

<!ELEMENT ENUM_ENTRY (REGULAR_CMT?, REPEATABLE_CMT?)>
  <!ATTLIST ENUM_ENTRY NAME   	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY VALUE  	CDATA  #REQUIRED>
  <!ATTLIST ENUM_ENTRY COMMENT  CDATA  #REQUIRED>

]>
<PROGRAM NAME="th06_102h.exe" EXE_PATH="/home/mary/Downloads/touhou06_hopefully/Touhou6/&#x6771;&#x65B9;&#x7D05;&#x9B54;&#x90F7;.exe" EXE_FORMAT="Portable Executable (PE)" IMAGE_BASE="00400000">
    <INFO_SOURCE  />
    <PROCESSOR NAME="x86" LANGUAGE_PROVIDER="x86:LE:32:default:windows" ENDIAN="little" />
    <DATATYPES>
        <TYPE_DEF NAME="ATOM" NAMESPACE="/WinDef.h" DATATYPE="WORD" DATATYPE_NAMESPACE="/WinDef.h" />
        <TYPE_DEF NAME="BITMAPINFO" NAMESPACE="/wingdi.h" DATATYPE="tagBITMAPINFO" DATATYPE_NAMESPACE="/wingdi.h" />
        <TYPE_DEF NAME="BITMAPINFOHEADER" NAMESPACE="/wingdi.h" DATATYPE="tagBITMAPINFOHEADER" DATATYPE_NAMESPACE="/wingdi.h" />
        <TYPE_DEF NAME="BOOL" NAMESPACE="/WinDef.h" DATATYPE="int" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="BYTE" NAMESPACE="/WinDef.h" DATATYPE="uchar" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="CDocObjectServer" NAMESPACE="/Demangler" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <TYPE_DEF NAME="CHAR" NAMESPACE="/winnt.h" DATATYPE="char" DATATYPE_NAMESPACE="/" />
        <STRUCTURE NAME="CLIENT_ID" NAMESPACE="/" SIZE="0x8">
            <MEMBER OFFSET="0x0" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="UniqueProcess" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="void *" DATATYPE_NAMESPACE="/" NAME="UniqueThread" SIZE="0x4" />
        </STRUCTURE>
        <TYPE_DEF NAME="COLORREF" NAMESPACE="/WinDef.h" DATATYPE="DWORD" DATATYPE_NAMESPACE="/WinDef.h" />
        <TYPE_DEF NAME="CONTEXT" NAMESPACE="/winnt.h" DATATYPE="_CONTEXT" DATATYPE_NAMESPACE="/excpt.h" />
        <STRUCTURE NAME="COleDispParams" NAMESPACE="/Demangler" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <TYPE_DEF NAME="DWORD" NAMESPACE="/WinDef.h" DATATYPE="ulong" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="DWORD_PTR" NAMESPACE="/basetsd.h" DATATYPE="ULONG_PTR" DATATYPE_NAMESPACE="/basetsd.h" />
        <STRUCTURE NAME="EHExceptionRecord" NAMESPACE="/Demangler" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <STRUCTURE NAME="EHRegistrationNode" NAMESPACE="/Demangler" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <TYPE_DEF NAME="EXCEPTION_RECORD" NAMESPACE="/winnt.h" DATATYPE="_EXCEPTION_RECORD" DATATYPE_NAMESPACE="/excpt.h" />
        <TYPE_DEF NAME="FARPROC" NAMESPACE="/WinDef.h" DATATYPE="FARPROC *" DATATYPE_NAMESPACE="/WinDef.h/functions" />
        <FUNCTION_DEF NAME="FARPROC" NAMESPACE="/WinDef.h/functions">
            <REGULAR_CMT>Function Signature Data Type</REGULAR_CMT>
            <RETURN_TYPE DATATYPE="int" DATATYPE_NAMESPACE="/" SIZE="0x4" />
        </FUNCTION_DEF>
        <TYPE_DEF NAME="FILE" NAMESPACE="/mbstring.h" DATATYPE="_iobuf" DATATYPE_NAMESPACE="/mbstring.h" />
        <TYPE_DEF NAME="FILETIME" NAMESPACE="/WinDef.h" DATATYPE="_FILETIME" DATATYPE_NAMESPACE="/WinDef.h" />
        <TYPE_DEF NAME="FLOATING_SAVE_AREA" NAMESPACE="/winnt.h" DATATYPE="_FLOATING_SAVE_AREA" DATATYPE_NAMESPACE="/winnt.h" />
        <TYPE_DEF NAME="FOURCC" NAMESPACE="/mmsystem.h" DATATYPE="DWORD" DATATYPE_NAMESPACE="/WinDef.h" />
        <STRUCTURE NAME="FrameInfo" NAMESPACE="/Demangler" SIZE="0x0">
            <REGULAR_CMT>PlaceHolder Structure</REGULAR_CMT>
        </STRUCTURE>
        <TYPE_DEF NAME="FuncInfo" NAMESPACE="/" DATATYPE="_s_FuncInfo" DATATYPE_NAMESPACE="/" />
        <TYPE_DEF NAME="GUID" NAMESPACE="/guiddef.h" DATATYPE="_GUID" DATATYPE_NAMESPACE="/guiddef.h" />
        <STRUCTURE NAME="GameConfiguration" NAMESPACE="/th06" SIZE="0x38">
            <MEMBER OFFSET="0x0" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x5" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x6" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x7" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x8" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x9" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xa" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xb" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xc" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xd" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xe" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xf" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x10" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x11" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x12" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x13" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x14" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x15" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x16" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x17" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x18" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="lifeCount" SIZE="0x1" />
            <MEMBER OFFSET="0x19" DATATYPE="byte" DATATYPE_NAMESPACE="/" NAME="bombCount" SIZE="0x1" />
            <MEMBER OFFSET="0x1a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1c" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1d" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1e" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1f" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x20" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="padAxisX" SIZE="0x2" />
            <MEMBER OFFSET="0x22" DATATYPE="ushort" DATATYPE_NAMESPACE="/" NAME="padAxisY" SIZE="0x2" />
            <MEMBER OFFSET="0x24" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x25" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x26" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x27" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x28" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x29" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2c" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2d" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2e" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2f" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x30" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x31" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x32" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x33" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x34" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x35" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x36" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x37" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
        </STRUCTURE>
        <STRUCTURE NAME="GameContext" NAMESPACE="/th06" SIZE="0x150">
            <MEMBER OFFSET="0x0" DATATYPE="HINSTANCE" DATATYPE_NAMESPACE="/WinDef.h" NAME="hInstance" SIZE="0x4" />
            <MEMBER OFFSET="0x4" DATATYPE="IDirect3D8 *" DATATYPE_NAMESPACE="/d3d8.h" NAME="d3d_iface" SIZE="0x4" />
            <MEMBER OFFSET="0x8" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x9" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xa" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xb" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xc" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xd" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xe" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0xf" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x10" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x11" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x12" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x13" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x14" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x15" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x16" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x17" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x18" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x19" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1c" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1d" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1e" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x1f" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x20" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x21" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x22" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x23" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x24" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x25" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x26" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x27" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x28" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x29" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2c" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2d" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2e" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x2f" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x30" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x31" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x32" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x33" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x34" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x35" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x36" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x37" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x38" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x39" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3c" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3d" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3e" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x3f" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x40" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x41" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x42" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x43" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x44" DATATYPE="HWND" DATATYPE_NAMESPACE="/WinDef.h" NAME="hwndGameWindow" SIZE="0x4" />
            <MEMBER OFFSET="0x48" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x49" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4a" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4b" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4c" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4d" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4e" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x4f" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x50" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x51" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x52" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x53" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />
            <MEMBER OFFSET="0x54" DATATYPE="undefined" DATATYPE_NAMESPACE="/" SIZE="0x1" />